services:
  - type: web
    name: ollama-b-server
    env: docker
    dockerfilePath: ./Dockerfile
    # 改成我们带延时、等模型的启动脚本
    startCommand: ./start.sh
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434
      - key: PORT
        value: 11434
    plan: free
    autoDeploy: true
